<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <GameDir>..\..</GameDir>
    </PropertyGroup>
    
    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <AssemblyName>PowerwashSimAP</AssemblyName>
        <Product>PowerwashSimArchipelagoRandomizer</Product>
        <Version>0.6.0</Version>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>13</LangVersion>
        <RestoreAdditionalProjectSources>
            https://api.nuget.org/v3/index.json;
            https://nuget.bepinex.dev/v3/index.json;
            https://nuget.samboy.dev/v3/index.json
        </RestoreAdditionalProjectSources>
        <RootNamespace>PowerwashSimAP</RootNamespace>
    </PropertyGroup>

    <Target Name="CopyCustomContent" AfterTargets="AfterBuild">
        <Copy
                SourceFiles="bin/Debug/net48/PowerwashSimAP.dll"
                DestinationFolder="$(GameDir)/BepInEx/plugins/SW_CreeperKing.ArchipelagoMod"
        />
    </Target>

    <ItemGroup>
        <!--        <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.*" IncludeAssets="compile"/>-->
        <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*"/>
    </ItemGroup>

    <ItemGroup>
        <Reference Include="0Harmony">
            <HintPath>$(GameDir)\BepInEx\core\0Harmony.dll</HintPath>
        </Reference>
        <Reference Include="Assembly-CSharp">
            <HintPath>$(GameDir)\BepInEx\unhollowed\Assembly-CSharp.dll</HintPath>
        </Reference>
        <Reference Include="Assembly-CSharp-firstpass">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Assembly-CSharp-firstpass.dll</HintPath>
        </Reference>
        <Reference Include="Backtrace.Unity">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Backtrace.Unity.dll</HintPath>
        </Reference>
        <Reference Include="BepInEx.Core">
            <HintPath>$(GameDir)\BepInEx\core\BepInEx.Core.dll</HintPath>
        </Reference>
        <Reference Include="BepInEx.IL2CPP" IncludeAssets="compile">
            <HintPath>$(GameDir)\BepInEx\core\BepInEx.IL2CPP.dll</HintPath>
        </Reference>
        <Reference Include="BepInEx.Preloader.Core">
            <HintPath>$(GameDir)\BepInEx\core\BepInEx.Preloader.Core.dll</HintPath>
        </Reference>
        <Reference Include="BNG">
          <HintPath>$(GameDir)\BepInEx\unhollowed\BNG.dll</HintPath>
        </Reference>
        <Reference Include="BundledApClient">
          <HintPath>lib\BundledApClient.dll</HintPath>
        </Reference>
        <Reference Include="Dreamteck.Splines">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Dreamteck.Splines.dll</HintPath>
        </Reference>
        <Reference Include="Dreamteck.Utilities">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Dreamteck.Utilities.dll</HintPath>
        </Reference>
        <Reference Include="FMODUnity">
          <HintPath>$(GameDir)\BepInEx\unhollowed\FMODUnity.dll</HintPath>
        </Reference>
        <Reference Include="FMODUnityResonance">
          <HintPath>$(GameDir)\BepInEx\unhollowed\FMODUnityResonance.dll</HintPath>
        </Reference>
        <Reference Include="FuturLab">
          <HintPath>$(GameDir)\BepInEx\unhollowed\FuturLab.dll</HintPath>
        </Reference>
        <Reference Include="FuturLab.I2Extension">
          <HintPath>$(GameDir)\BepInEx\unhollowed\FuturLab.I2Extension.dll</HintPath>
        </Reference>
        <Reference Include="FuturLab.Steam">
          <HintPath>$(GameDir)\BepInEx\unhollowed\FuturLab.Steam.dll</HintPath>
        </Reference>
        <Reference Include="I2Localization">
          <HintPath>$(GameDir)\BepInEx\unhollowed\I2Localization.dll</HintPath>
        </Reference>
        <Reference Include="Il2CppMono.Security">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Il2CppMono.Security.dll</HintPath>
        </Reference>
        <Reference Include="Il2Cppmscorlib">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Il2Cppmscorlib.dll</HintPath>
        </Reference>
        <Reference Include="Il2CppSystem">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Il2CppSystem.dll</HintPath>
        </Reference>
        <Reference Include="Il2CppSystem.Buffers">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Il2CppSystem.Buffers.dll</HintPath>
        </Reference>
        <Reference Include="Il2CppSystem.Configuration">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Il2CppSystem.Configuration.dll</HintPath>
        </Reference>
        <Reference Include="Il2CppSystem.Core">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Il2CppSystem.Core.dll</HintPath>
        </Reference>
        <Reference Include="Il2CppSystem.Data">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Il2CppSystem.Data.dll</HintPath>
        </Reference>
        <Reference Include="Il2CppSystem.IO.Compression">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Il2CppSystem.IO.Compression.dll</HintPath>
        </Reference>
        <Reference Include="Il2CppSystem.Memory">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Il2CppSystem.Memory.dll</HintPath>
        </Reference>
        <Reference Include="Il2CppSystem.Numerics">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Il2CppSystem.Numerics.dll</HintPath>
        </Reference>
        <Reference Include="Il2CppSystem.Numerics.Vectors">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Il2CppSystem.Numerics.Vectors.dll</HintPath>
        </Reference>
        <Reference Include="Il2CppSystem.Runtime.CompilerServices.Unsafe">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Il2CppSystem.Runtime.CompilerServices.Unsafe.dll</HintPath>
        </Reference>
        <Reference Include="Il2CppSystem.Runtime.Serialization">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Il2CppSystem.Runtime.Serialization.dll</HintPath>
        </Reference>
        <Reference Include="Il2CppSystem.Threading.Tasks.Extensions">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Il2CppSystem.Threading.Tasks.Extensions.dll</HintPath>
        </Reference>
        <Reference Include="Il2CppSystem.Xml">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Il2CppSystem.Xml.dll</HintPath>
        </Reference>
        <Reference Include="Il2CppSystem.Xml.Linq">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Il2CppSystem.Xml.Linq.dll</HintPath>
        </Reference>
        <Reference Include="JBooth.MicroSplat.Core">
          <HintPath>$(GameDir)\BepInEx\unhollowed\JBooth.MicroSplat.Core.dll</HintPath>
        </Reference>
        <Reference Include="LinkedTerrainCore">
          <HintPath>$(GameDir)\BepInEx\unhollowed\LinkedTerrainCore.dll</HintPath>
        </Reference>
        <Reference Include="MeshBakerCore">
          <HintPath>$(GameDir)\BepInEx\unhollowed\MeshBakerCore.dll</HintPath>
        </Reference>
        <Reference Include="MessagePack">
          <HintPath>$(GameDir)\BepInEx\unhollowed\MessagePack.dll</HintPath>
        </Reference>
        <Reference Include="MessagePack.Annotations">
          <HintPath>$(GameDir)\BepInEx\unhollowed\MessagePack.Annotations.dll</HintPath>
        </Reference>
        <Reference Include="MLAPI Community Extensions">
          <HintPath>$(GameDir)\BepInEx\unhollowed\MLAPI Community Extensions.dll</HintPath>
        </Reference>
        <Reference Include="Newtonsoft.Json">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Newtonsoft.Json.dll</HintPath>
        </Reference>
        <Reference Include="PerfectCulling">
          <HintPath>$(GameDir)\BepInEx\unhollowed\PerfectCulling.dll</HintPath>
        </Reference>
        <Reference Include="Photon Realtime MLAPI Transport">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Photon Realtime MLAPI Transport.dll</HintPath>
        </Reference>
        <Reference Include="Photon3Unity3D">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Photon3Unity3D.dll</HintPath>
        </Reference>
        <Reference Include="PlayFab">
          <HintPath>$(GameDir)\BepInEx\unhollowed\PlayFab.dll</HintPath>
        </Reference>
        <Reference Include="ProceduralWorlds.SceneOptimizer.Core">
          <HintPath>$(GameDir)\BepInEx\unhollowed\ProceduralWorlds.SceneOptimizer.Core.dll</HintPath>
        </Reference>
        <Reference Include="PWS">
            <HintPath>$(GameDir)\BepInEx\unhollowed\PWS.dll</HintPath>
        </Reference>
        <Reference Include="PWSBackend.Shared">
          <HintPath>$(GameDir)\BepInEx\unhollowed\PWSBackend.Shared.dll</HintPath>
        </Reference>
        <Reference Include="Rewired">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Rewired.dll</HintPath>
        </Reference>
        <Reference Include="Rewired_Core">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Rewired_Core.dll</HintPath>
        </Reference>
        <Reference Include="Rewired_Windows">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Rewired_Windows.dll</HintPath>
        </Reference>
        <Reference Include="SevenZip">
          <HintPath>$(GameDir)\BepInEx\unhollowed\SevenZip.dll</HintPath>
        </Reference>
        <Reference Include="Sirenix.OdinInspector.Attributes">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Sirenix.OdinInspector.Attributes.dll</HintPath>
        </Reference>
        <Reference Include="Steamworks.NET">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Steamworks.NET.dll</HintPath>
        </Reference>
        <Reference Include="System.Data.Linq" />
        <Reference Include="UnhollowerBaseLib">
            <HintPath>$(GameDir)\BepInEx\core\UnhollowerBaseLib.dll</HintPath>
        </Reference>
        <Reference Include="UnhollowerRuntimeLib">
            <HintPath>$(GameDir)\BepInEx\core\UnhollowerRuntimeLib.dll</HintPath>
        </Reference>
        <Reference Include="Unity.Addressables">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Unity.Addressables.dll</HintPath>
        </Reference>
        <Reference Include="Unity.Animation.Rigging">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Unity.Animation.Rigging.dll</HintPath>
        </Reference>
        <Reference Include="Unity.Burst">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Unity.Burst.dll</HintPath>
        </Reference>
        <Reference Include="Unity.Burst.Unsafe">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Unity.Burst.Unsafe.dll</HintPath>
        </Reference>
        <Reference Include="Unity.Collections">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Unity.Collections.dll</HintPath>
        </Reference>
        <Reference Include="Unity.InputSystem">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Unity.InputSystem.dll</HintPath>
        </Reference>
        <Reference Include="Unity.Mathematics">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Unity.Mathematics.dll</HintPath>
        </Reference>
        <Reference Include="Unity.Multiplayer.MLAPI.Prototyping">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Unity.Multiplayer.MLAPI.Prototyping.dll</HintPath>
        </Reference>
        <Reference Include="Unity.Multiplayer.MLAPI.Runtime">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Unity.Multiplayer.MLAPI.Runtime.dll</HintPath>
        </Reference>
        <Reference Include="Unity.Polybrush">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Unity.Polybrush.dll</HintPath>
        </Reference>
        <Reference Include="Unity.ProBuilder">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Unity.ProBuilder.dll</HintPath>
        </Reference>
        <Reference Include="Unity.RenderPipeline.Universal.ShaderLibrary">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Unity.RenderPipeline.Universal.ShaderLibrary.dll</HintPath>
        </Reference>
        <Reference Include="Unity.RenderPipelines.Core.Runtime">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Unity.RenderPipelines.Core.Runtime.dll</HintPath>
        </Reference>
        <Reference Include="Unity.RenderPipelines.Universal.Runtime">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Unity.RenderPipelines.Universal.Runtime.dll</HintPath>
        </Reference>
        <Reference Include="Unity.ResourceManager">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Unity.ResourceManager.dll</HintPath>
        </Reference>
        <Reference Include="Unity.TextMeshPro">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Unity.TextMeshPro.dll</HintPath>
        </Reference>
        <Reference Include="Unity.Timeline">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Unity.Timeline.dll</HintPath>
        </Reference>
        <Reference Include="Unity.VisualEffectGraph.Runtime">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Unity.VisualEffectGraph.Runtime.dll</HintPath>
        </Reference>
        <Reference Include="Unity.XR.CoreUtils">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Unity.XR.CoreUtils.dll</HintPath>
        </Reference>
        <Reference Include="Unity.XR.Interaction.Toolkit">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Unity.XR.Interaction.Toolkit.dll</HintPath>
        </Reference>
        <Reference Include="Unity.XR.Management">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Unity.XR.Management.dll</HintPath>
        </Reference>
        <Reference Include="Unity.XR.OpenXR">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Unity.XR.OpenXR.dll</HintPath>
        </Reference>
        <Reference Include="Unity.XR.OpenXR.Features.ConformanceAutomation">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Unity.XR.OpenXR.Features.ConformanceAutomation.dll</HintPath>
        </Reference>
        <Reference Include="Unity.XR.OpenXR.Features.MetaQuestSupport">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Unity.XR.OpenXR.Features.MetaQuestSupport.dll</HintPath>
        </Reference>
        <Reference Include="Unity.XR.OpenXR.Features.MockRuntime">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Unity.XR.OpenXR.Features.MockRuntime.dll</HintPath>
        </Reference>
        <Reference Include="Unity.XR.OpenXR.Features.OculusQuestSupport">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Unity.XR.OpenXR.Features.OculusQuestSupport.dll</HintPath>
        </Reference>
        <Reference Include="Unity.XR.OpenXR.Features.RuntimeDebugger">
          <HintPath>$(GameDir)\BepInEx\unhollowed\Unity.XR.OpenXR.Features.RuntimeDebugger.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine">
            <HintPath>$(GameDir)\BepInEx\unity-libs\UnityEngine.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.AccessibilityModule">
          <HintPath>$(GameDir)\BepInEx\unity-libs\UnityEngine.AccessibilityModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.AIModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.AIModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.AndroidJNIModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.AndroidJNIModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.AnimationModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.AnimationModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.AssetBundleModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.AssetBundleModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.AudioModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.AudioModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.ClothModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.ClothModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.ClusterInputModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.ClusterInputModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.ClusterRendererModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.ClusterRendererModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.CoreModule">
          <HintPath>$(GameDir)\BepInEx\unity-libs\UnityEngine.CoreModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.CrashReportingModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.CrashReportingModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.DirectorModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.DirectorModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.DSPGraphModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.DSPGraphModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.GameCenterModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.GameCenterModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.GIModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.GIModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.GridModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.GridModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.HotReloadModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.HotReloadModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.ImageConversionModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.ImageConversionModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.IMGUIModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.IMGUIModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.InputLegacyModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.InputLegacyModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.InputModule">
          <HintPath>$(GameDir)\BepInEx\unity-libs\UnityEngine.InputModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.JSONSerializeModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.JSONSerializeModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.LocalizationModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.LocalizationModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.ParticleSystemModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.ParticleSystemModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.PerformanceReportingModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.PerformanceReportingModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.Physics2DModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.Physics2DModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.PhysicsModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.PhysicsModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.ProfilerModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.ProfilerModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule">
          <HintPath>$(GameDir)\BepInEx\unity-libs\UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.ScreenCaptureModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.ScreenCaptureModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.SharedInternalsModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.SharedInternalsModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.SpatialTracking">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.SpatialTracking.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.SpriteMaskModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.SpriteMaskModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.SpriteShapeModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.SpriteShapeModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.StreamingModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.StreamingModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.SubstanceModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.SubstanceModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.SubsystemsModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.SubsystemsModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.TerrainModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.TerrainModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.TerrainPhysicsModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.TerrainPhysicsModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.TextCoreModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.TextCoreModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.TextRenderingModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.TextRenderingModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.TilemapModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.TilemapModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.TLSModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.TLSModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UI">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.UI.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UIElementsModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.UIElementsModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UIElementsNativeModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.UIElementsNativeModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UIModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.UIModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UmbraModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.UmbraModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UNETModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.UNETModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityAnalyticsCommonModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.UnityAnalyticsCommonModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityAnalyticsModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.UnityAnalyticsModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityConnectModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.UnityConnectModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityCurlModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.UnityCurlModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityTestProtocolModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.UnityTestProtocolModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityWebRequestAssetBundleModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.UnityWebRequestAssetBundleModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityWebRequestAudioModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.UnityWebRequestAudioModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityWebRequestModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.UnityWebRequestModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityWebRequestTextureModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.UnityWebRequestTextureModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityWebRequestWWWModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.UnityWebRequestWWWModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.VehiclesModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.VehiclesModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.VFXModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.VFXModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.VideoModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.VideoModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.VirtualTexturingModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.VirtualTexturingModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.VRModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.VRModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.WindModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.WindModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.XRModule">
          <HintPath>$(GameDir)\BepInEx\unhollowed\UnityEngine.XRModule.dll</HintPath>
        </Reference>
        <Reference Include="URPGrabPass">
          <HintPath>$(GameDir)\BepInEx\unhollowed\URPGrabPass.dll</HintPath>
        </Reference>
        <Reference Include="VisualDesignCafe.Nature">
          <HintPath>$(GameDir)\BepInEx\unhollowed\VisualDesignCafe.Nature.dll</HintPath>
        </Reference>
        <Reference Include="VisualDesignCafe.Packages">
          <HintPath>$(GameDir)\BepInEx\unhollowed\VisualDesignCafe.Packages.dll</HintPath>
        </Reference>
        <Reference Include="VisualDesignCafe.ShaderX">
          <HintPath>$(GameDir)\BepInEx\unhollowed\VisualDesignCafe.ShaderX.dll</HintPath>
        </Reference>
        <Reference Include="VLB">
          <HintPath>$(GameDir)\BepInEx\unhollowed\VLB.dll</HintPath>
        </Reference>
        <Reference Include="XGamingRuntime">
          <HintPath>$(GameDir)\BepInEx\unhollowed\XGamingRuntime.dll</HintPath>
        </Reference>
        <Reference Include="ZstdSharp">
          <HintPath>$(GameDir)\BepInEx\unhollowed\ZstdSharp.dll</HintPath>
        </Reference>
    </ItemGroup>
</Project>
